apiVersion: v1
kind: Pod
metadata:
  name: intra-pod-startup
spec:
  containers:
  - name: nginx
    image: thockin/nginx-from-git
    command:
    - /start.sh
    volumeMounts:
    - name: content
      mountPath: /usr/share/nginx/html
      readOnly: true
  - name: git-sync
    image: gcr.io/google_containers/git-sync
    volumeMounts:
    - name: content
      mountPath: /data
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/kubernetes/kubernetes
    - name: GIT_SYNC_DEST
      value: /data/kubernetes
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    - name: GIT_SYNC_DEPTH
      value: "1"
  volumes:
  - name: content
